# Generated by Django 5.0.2 on 2024-02-23 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_newuser_groups_newuser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='creation_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
