# Generated by Django 5.0.2 on 2024-02-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_newuser_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='nickname',
            field=models.CharField(default='User_<built-in method today of type object at 0x00007FF861E2EDD0>', max_length=100, unique=True),
        ),
    ]
