# Generated by Django 5.0.2 on 2024-02-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_newuser_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='nickname',
            field=models.CharField(default='User_<built-in method today of type object at 0x00007FF8621EEDD0>', max_length=100, unique=True),
        ),
    ]
