# Generated by Django 5.0.2 on 2024-02-23 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_creationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='creationDate',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(error_messages={'unique': 'File with same title already exists!'}, max_length=100, unique=True),
        ),
    ]
