# Generated by Django 5.0.2 on 2024-02-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(default='Note_<built-in method today of type object at 0x00007FF8621EEDD0>', error_messages={'unique': 'File with same title already exists!'}, max_length=100, unique=True),
        ),
    ]
