# Generated by Django 5.0.2 on 2024-02-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_note_lastupdate_note_user_alter_note_creationdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='lastUpdate',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(default='Note_<built-in method today of type object at 0x00007FF859FAEDD0>', error_messages={'unique': 'File with same title already exists!'}, max_length=100, unique=True),
        ),
    ]
