# Generated by Django 5.0.2 on 2024-02-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_alter_note_content_alter_note_lastupdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='lastUpdate',
            field=models.IntegerField(blank=True, default=1708973143210.8433, null=True),
        ),
    ]
