# Generated by Django 5.0.2 on 2024-03-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_alter_note_lastupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='lastUpdate',
            field=models.IntegerField(blank=True, default=1709675177529.6577, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(default='Note_<built-in method today of type object at 0x00007FF8EEE6EDD0>', max_length=100),
        ),
    ]
